=== symbolthree/rangehood/RANGEHOOD.DTD
<?xml version="1.0" encoding="UTF-8"?>
<!--
+================================================
|  RANGEHOOD Configuration File
+================================================
-->
<!ELEMENT RANGEHOOD (PROFILE+)>
<!ELEMENT PROFILE   (DATABASE, TITLE, DBOBJECT+)>
<!ELEMENT DATABASE  (URL, USERNAME, PASSWORD)>
<!ELEMENT URL       (#PCDATA)>
<!ELEMENT USERNAME  (#PCDATA)>
<!ELEMENT PASSWORD  (#PCDATA)>
<!ELEMENT TITLE     (#PCDATA)>
<!ATTLIST PROFILE
	append   (Y | N)  #REQUIRED
	name     CDATA    #REQUIRED
	output   CDATA    #REQUIRED
	template CDATA    #REQUIRED
>
<!ELEMENT DBOBJECT EMPTY>
<!ATTLIST DBOBJECT
    owner   CDATA #REQUIRED
	type    (ALL|TABLE|FUNCTION|PROCEDURE|PACKAGE|VIEW|SEQUENCE|TRIGGER|MVIEW|TYPE) #REQUIRED
 	include (Y | N)   #REQUIRED
	name    CDATA     #REQUIRED
>

=== symbolthree/rangehood/RANGEHOOD.XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RANGEHOOD SYSTEM "RANGEHOOD.dtd">
<!--
+================================================
|  RANGEHOOD Configuration File
|
|  Definition
|  ==========
|  /RANGEHOOD                    Root node
|
|  /RANGEHOOD/PROFILE            You can have multiple profiles in this configuration file with distinct profile name
|
|  /RANGEHOOD/PROFILE/@name      Profile name. This name can be passed as argument to the batch file.
|                                The default profile is "DEFAULT", which is used if no argment is used to run the program
|
|  /RANGEHOOD/PROFILE/@output    Output directory name. It can be relative path (w.r.t. install dir) or full qualified path                  
|
|  /RANGEHOOD/PROFILE/@template  Template name for this profile. There must be a directory have the same name under the
|                                installed directory. Standard installation provides 2 profiles: FANCY or SIMPLE
|
|  /RANGEHOOD/PROFILE/@append    Append Mode. If 'Y' template files will not be copied and DBOBJECT info will be 
|                                added / overwritten to the data generated from the previous run.
|                                If 'N' template files will be copied to output directory; new dbObject files will be created.
|
|  /RANGEHOOD/PROFILE/DATABASE   This node contains database connection info: JDBC URL, USERNAME, and PASSWORD.
|
|  /RANGEHOOD/PROFILE/TITLE      Documentation title displayed in the header of all pages
|
|  /RANGEHOOD/PROFILE/DBOBJECT   Each profile can have multiple DBOBJECT node, and you can put include or exclude information
|                                in each node.
|
|  /RANGEHOOD/PROFILE/DBOBJECT/@owner     schema name of that objects are under
|
|  /RANGEHOOD/PROFILE/DBOBJECT/@include   Value 'Y' if wildcard object names are included; 'N' to exclude specified objects
|          
|  /RANGEHOOD/PROFILE/DBOBJECT/@type      Possible values are: ALL,TABLE,FUNCTION,PROCEDURE,PACKAGE,VIEW,SEQUENCE,TRIGGER,MVIEW,TYPE
|
|  /RANGEHOOD/PROFILE/DBOBJECT/@name      DBOBject name. Wildcard character (%) can be used.
|
+================================================
-->
<RANGEHOOD>
	<PROFILE name="DEFAULT" output="DEFAULT" template="FANCY" append="N">
		<DATABASE>
			<URL>jdbc:oracle:thin:@192.168.0.106:1521:R12</URL>
			<USERNAME>APPS</USERNAME>
			<PASSWORD>APPS</PASSWORD>
		</DATABASE>
		<TITLE>Oracle EBS MTL ITEM PACKAGES</TITLE>
		<!-- <DBOBJECT owner="INV" include="Y" type="ALL" name="MTL%ITEM%"/> -->
		<DBOBJECT owner="APPS" include="Y" type="PACKAGE" name="MTL%ITEM%"/>
	</PROFILE>
	<PROFILE name="GL_EXAMPLE" output="GL_EXAMPLE" template="FANCY" append="N">
		<DATABASE>
			<URL>jdbc:oracle:thin:@192.168.0.106:1521:R12</URL>
			<USERNAME>APPS</USERNAME>
			<PASSWORD>APPS</PASSWORD>
		</DATABASE>
		<DBOBJECT owner="GL" include="Y" type="ALL" name="GL%J%"/>
		<DBOBJECT owner="APPS" include="Y" type="ALL" name="GL%J%"/>
	</PROFILE>	
</RANGEHOOD>
